### PR TITLE
feat: add `date` placeholder modifier with sophisticated date/time modification expressions

### LINKED ISSUE #270: custom date in placeholder / lastDayOfMonth
**Is your feature request related to a problem? Please describe.**
I get emails with attachments on 4-6th of each month (random). I'd like to save the attachment with the date of the last day of the previous month, i.e. if the email comes on 4/2/2024 I'd like the filename to be `2024-01-31_filename.pdf`

**Describe the solution you'd like**
I'd like to be able to either set `date.custom` to `2024-02-01` and then subtract offset 1 day (2024-02-01 - 1day) using `offset-format`, or use a placeholder like [lastDayOfMonth](https://date-fns.org/v3.2.0/docs/lastDayOfMonth)

**Describe alternatives you've considered**
using [offset-format feature](https://github.com/ahochsteger/gmail-processor/pull/143) with `date.now` or `message.date` - however I can't get consistent results with this method since emails arrive on unpredictable dates

thank you

### PR DESCRIPTION
**Pull request by ahochsteger**
# Description

This PR adds support for date-fns expressions like `lastDayOfMonth` in substitution placeholder of the form `${<placeholder>:date:<expression>[:<format>]}` to allow for more sophisticated date calculations.
An expression can consist of an optional [supported `date-fns` function](https://github.com/ahochsteger/gmail-processor/blob/28282a1b97169d86014550ea98db164362e39ba3/src/lib/utils/DateUtils.ts#L58) followed by an optional parse-duration expression.

Here are some examples:
* `${message.date:date:lastDayOfMonth-1d:yyyy-MM-DD}` -> evaluates to the 2nd last day of the month in which the message has been sent. 
* `${message.body.match.invoiceDate:date:startOfMonth+4d+1month:yyyy-MM-DD}` -> evaluates to the 5th day of the month following the invoice date (extracted using a regex from the message body)

Fixes #270

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How has this been tested?

The date expressions are tested using the following unit tests:

- [x] [src/lib/utils/DateUtils.spec.ts](src/lib/utils/DateUtils.spec.ts)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes

### CODE REVIEW

**Comment by chrismazanec** [comment]
@ahochsteger can you please give an example, with this PR, how would I get a date of the last day of previous month?

message arrives on 4/feb/2024, what do I need to set to get the last day of previous month? (2024-01-31)
`${message.date:date-expr:lastDayOfMonth-1months:yyyy-MM-dd}`
would return `2024-01-29` in this case, no?

**Comment by chrismazanec** [comment]
@ahochsteger can you please give an example, with this PR, how would I get a date of the last day of previous month?

message arrives on 4/feb/2024, to get the last day of previous month? (2024-01-31)
`${message.date:date-expr:startOfMonth-1d:yyyy-MM-dd}` 

is this correct? thank you

**Comment by ahochsteger** [comment]
> @ahochsteger can you please give an example, with this PR, how would I get a date of the last day of previous month?
> 
> message arrives on 4/feb/2024, to get the last day of previous month? (2024-01-31) `${message.date:date-expr:startOfMonth-1d:yyyy-MM-dd}`
> 
> is this correct? thank you

@chrismazanec in principle yes, but the PR is still work-in-progress since I'm thinking about ways to introduce a general expression language syntax that is not only usable for dates but for other types as well.
In case you wanted to try the current development state it should work the way you wanted, but the build and deployment did not yet work until today.

I'd be happy to get some feedback and suggestions to make it more usable.

**Comment by ahochsteger** [comment]
@chrismazanec the PR is now ready from my point of view, it would be great, if you could give it a try.
The syntax has changed slightly from `date-expr` to just `date` in preparation for #260 to allow extracted strings to be converted into a date as well.

**Comment by chrismazanec** [comment]
> @chrismazanec the PR is now ready from my point of view, it would be great, if you could give it a try. The syntax has changed slightly from `date-expr` to just `date` in preparation for #260 to allow extracted strings to be converted into a date as well.

@ahochsteger this is awesome, I've tested it, and works like a charm! thank you 🙏

I recommend adding this example to docs too:
```
${message.date:date:startOfMonth-1d:yyyy-MM-dd}
```
- last day of the previous month

**Pull request merged**
